//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTService.ServiceReferenceTravelData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TravelSendInfo", Namespace="http://schemas.datacontract.org/2004/07/RESTService")]
    [System.SerializableAttribute()]
    public partial class TravelSendInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string arrivalLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int orderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnlDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string arrivalLocation {
            get {
                return this.arrivalLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.arrivalLocationField, value) != true)) {
                    this.arrivalLocationField = value;
                    this.RaisePropertyChanged("arrivalLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureDate {
            get {
                return this.departureDateField;
            }
            set {
                if ((object.ReferenceEquals(this.departureDateField, value) != true)) {
                    this.departureDateField = value;
                    this.RaisePropertyChanged("departureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureLocation {
            get {
                return this.departureLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.departureLocationField, value) != true)) {
                    this.departureLocationField = value;
                    this.RaisePropertyChanged("departureLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderID {
            get {
                return this.orderIDField;
            }
            set {
                if ((this.orderIDField.Equals(value) != true)) {
                    this.orderIDField = value;
                    this.RaisePropertyChanged("orderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string returnlDate {
            get {
                return this.returnlDateField;
            }
            set {
                if ((object.ReferenceEquals(this.returnlDateField, value) != true)) {
                    this.returnlDateField = value;
                    this.RaisePropertyChanged("returnlDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TravelReceiveInfo", Namespace="http://schemas.datacontract.org/2004/07/RESTService")]
    [System.SerializableAttribute()]
    public partial class TravelReceiveInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string arrivalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float discountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string googleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] passengerDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string planeCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string planeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string arrivalName {
            get {
                return this.arrivalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.arrivalNameField, value) != true)) {
                    this.arrivalNameField = value;
                    this.RaisePropertyChanged("arrivalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureDate {
            get {
                return this.departureDateField;
            }
            set {
                if ((object.ReferenceEquals(this.departureDateField, value) != true)) {
                    this.departureDateField = value;
                    this.RaisePropertyChanged("departureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureName {
            get {
                return this.departureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.departureNameField, value) != true)) {
                    this.departureNameField = value;
                    this.RaisePropertyChanged("departureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float discount {
            get {
                return this.discountField;
            }
            set {
                if ((this.discountField.Equals(value) != true)) {
                    this.discountField = value;
                    this.RaisePropertyChanged("discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string googleID {
            get {
                return this.googleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.googleIDField, value) != true)) {
                    this.googleIDField = value;
                    this.RaisePropertyChanged("googleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] passengerData {
            get {
                return this.passengerDataField;
            }
            set {
                if ((object.ReferenceEquals(this.passengerDataField, value) != true)) {
                    this.passengerDataField = value;
                    this.RaisePropertyChanged("passengerData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string planeCompany {
            get {
                return this.planeCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.planeCompanyField, value) != true)) {
                    this.planeCompanyField = value;
                    this.RaisePropertyChanged("planeCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string planeName {
            get {
                return this.planeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.planeNameField, value) != true)) {
                    this.planeNameField = value;
                    this.RaisePropertyChanged("planeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string returnDate {
            get {
                return this.returnDateField;
            }
            set {
                if ((object.ReferenceEquals(this.returnDateField, value) != true)) {
                    this.returnDateField = value;
                    this.RaisePropertyChanged("returnDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Passenger", Namespace="http://schemas.datacontract.org/2004/07/RESTService")]
    [System.SerializableAttribute()]
    public partial class Passenger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int passengerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int passengerID {
            get {
                return this.passengerIDField;
            }
            set {
                if ((this.passengerIDField.Equals(value) != true)) {
                    this.passengerIDField = value;
                    this.RaisePropertyChanged("passengerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTravelData.IServiceTravelData")]
    public interface IServiceTravelData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTravelData/ReturnTravels", ReplyAction="http://tempuri.org/IServiceTravelData/ReturnTravelsResponse")]
        RESTService.ServiceReferenceTravelData.TravelSendInfo[] ReturnTravels(string googleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTravelData/ReturnTravels", ReplyAction="http://tempuri.org/IServiceTravelData/ReturnTravelsResponse")]
        System.Threading.Tasks.Task<RESTService.ServiceReferenceTravelData.TravelSendInfo[]> ReturnTravelsAsync(string googleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTravelData/AddTravel", ReplyAction="http://tempuri.org/IServiceTravelData/AddTravelResponse")]
        void AddTravel(RESTService.ServiceReferenceTravelData.TravelReceiveInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTravelData/AddTravel", ReplyAction="http://tempuri.org/IServiceTravelData/AddTravelResponse")]
        System.Threading.Tasks.Task AddTravelAsync(RESTService.ServiceReferenceTravelData.TravelReceiveInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTravelData/RemoveTravel", ReplyAction="http://tempuri.org/IServiceTravelData/RemoveTravelResponse")]
        void RemoveTravel(string googleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTravelData/RemoveTravel", ReplyAction="http://tempuri.org/IServiceTravelData/RemoveTravelResponse")]
        System.Threading.Tasks.Task RemoveTravelAsync(string googleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTravelData/ReturnPassengers", ReplyAction="http://tempuri.org/IServiceTravelData/ReturnPassengersResponse")]
        RESTService.ServiceReferenceTravelData.Passenger[] ReturnPassengers(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTravelData/ReturnPassengers", ReplyAction="http://tempuri.org/IServiceTravelData/ReturnPassengersResponse")]
        System.Threading.Tasks.Task<RESTService.ServiceReferenceTravelData.Passenger[]> ReturnPassengersAsync(string orderID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTravelDataChannel : RESTService.ServiceReferenceTravelData.IServiceTravelData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTravelDataClient : System.ServiceModel.ClientBase<RESTService.ServiceReferenceTravelData.IServiceTravelData>, RESTService.ServiceReferenceTravelData.IServiceTravelData {
        
        public ServiceTravelDataClient() {
        }
        
        public ServiceTravelDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTravelDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTravelDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTravelDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RESTService.ServiceReferenceTravelData.TravelSendInfo[] ReturnTravels(string googleID) {
            return base.Channel.ReturnTravels(googleID);
        }
        
        public System.Threading.Tasks.Task<RESTService.ServiceReferenceTravelData.TravelSendInfo[]> ReturnTravelsAsync(string googleID) {
            return base.Channel.ReturnTravelsAsync(googleID);
        }
        
        public void AddTravel(RESTService.ServiceReferenceTravelData.TravelReceiveInfo info) {
            base.Channel.AddTravel(info);
        }
        
        public System.Threading.Tasks.Task AddTravelAsync(RESTService.ServiceReferenceTravelData.TravelReceiveInfo info) {
            return base.Channel.AddTravelAsync(info);
        }
        
        public void RemoveTravel(string googleID) {
            base.Channel.RemoveTravel(googleID);
        }
        
        public System.Threading.Tasks.Task RemoveTravelAsync(string googleID) {
            return base.Channel.RemoveTravelAsync(googleID);
        }
        
        public RESTService.ServiceReferenceTravelData.Passenger[] ReturnPassengers(string orderID) {
            return base.Channel.ReturnPassengers(orderID);
        }
        
        public System.Threading.Tasks.Task<RESTService.ServiceReferenceTravelData.Passenger[]> ReturnPassengersAsync(string orderID) {
            return base.Channel.ReturnPassengersAsync(orderID);
        }
    }
}
